# Generated by Django 4.2.7 on 2023-12-23 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_products_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='categoria',
            field=models.CharField(default='Producto', max_length=100),
        ),
    ]
