# Generated by Django 4.2.7 on 2023-12-24 19:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientes', '0005_contacto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_postal', models.IntegerField()),
                ('region', models.CharField(max_length=255)),
                ('ciudad', models.CharField(max_length=255)),
                ('comuna', models.CharField(max_length=255)),
                ('calle', models.CharField(max_length=255)),
                ('casa_depto', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
