# Generated by Django 4.2.7 on 2023-12-24 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_alter_direccion_calle_alter_direccion_ciudad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valoracion',
            name='puntuacion',
        ),
    ]
